### ISSUE TITLE
How to talk to multiple control units arbitration ID wise?

### ISSUE THREAD

**Issue by brandonros** [Automotive-Swift/Swift-UDS#1]
For example, you need to request seed/key on Mercedes to EZS213/EZS167 for diagnostic firewall unlock, then keep tester present alive on interval.

```javascript
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms))

const hex2ArrayBuffer = (hex) => {
  return new Uint8Array(hex.match(/[\da-f]{2}/gi).map(function (h) {
    return parseInt(h, 16)
  }))
}

const buf2hex = (buffer) => {
  return [...new Uint8Array(buffer)]
    .map(x => x.toString(16).padStart(2, '0'))
    .join('')
}

const strToHex = (str) => {
  let result = '';
  for (let i = 0; i < str.length; ++i) {
    result += str.charCodeAt(i).toString(16).padStart(2, '0')
  }
  return result
}

const initDevice = async () => {
  const deviceName = 'IOS-Vlink'
  const serviceUuid = 'e7810a71-73ae-499d-8c15-faa9aef0c3f2'
  const characteristicUuid = 'bef8d6c9-9c21-4c9e-b632-bd58c1009f9f'

  const options = {
    filters: [
      { name: deviceName }
    ],
    optionalServices: [
      serviceUuid
    ]
  }
  const device = await navigator.bluetooth.requestDevice(options)
  const server = await device.gatt.connect()
  const service = await server.getPrimaryService(serviceUuid)
  const characteristic = await service.getCharacteristic(characteristicUuid)
  characteristic.startNotifications()
  characteristic.addEventListener('characteristicvaluechanged', (event) => {
    console.log(buf2hex(event.target.value.buffer))
  })
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATZ\r'))) // reset
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATE0\r'))) // echo off
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATS0\r'))) // spacing off
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATSP6\r'))) // 6 – ISO 15765-4 CAN (11 bit ID, 500 kbaud)
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATH1\r'))) // headers on
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATFC0\r'))) // flow control off
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATAL\r'))) // allow long messages
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATCRA7ED\r'))) // set receive address
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('ATSH7E5\r'))) // set header
  await delay(1000)
  await characteristic.writeValue(hex2ArrayBuffer(strToHex('3E00\r'))) // tester present
  await delay(1000)
}

initDevice()
```

That is enough to talk to CPC_NG, but how do you receive from CPC_NG and MED1775 and VGSNAG3? How can you send to CPC_NG and EZS213 at the same time? Do you have to set header each time?

**Comment by mickeyl** [comment]
(This is not really a question about Swift-UDS, but an interesting problem)

If you have to overcome a diagnostic firewall that needs a regular `0x3E 0x00` being sent, you basically have two choices:

1. Register a timer and send the necessary commands (i.e. `ATSH`, `ATCRA`, `3e00`) _in-between_ your normal communication. While Swift-UDS does not have such an API, it would be pretty easy to add one.
This works with every adapter.

2. Rely on special adapter behavior. Many adapters that are designed for ECU coding and reprogramming also come with a special command set for periodic messaging, e.g., the STN-based family (OBDLINK MX+ and all the others) have the command `STPPMA period, header, data` which does exactly that.
This is a much better way than 1., since the microcontroller on the adapter is handling the timing issues.

As a matter of fact, my own custom flasher (which is using Swift-UDS) will support EZS213/EZS167 later this year, so I will add both strategies into the code soon.

**Comment by brandonros** [comment]
> (This is not really a question about Swift-UDS, but an interesting problem)

Yes.

Do you know who I am by the way?

**Comment by mickeyl** [comment]
Let me reopen this to keep track over my this feature which should land in this repository within the next 48 hours.

I'm currently working on the last missing bits to enable unlocking the EZS (and keeping it unlocked), which is by augmenting the [Pipeline](https://github.com/Automotive-Swift/Swift-UDS/blob/master/Sources/Swift-UDS-Adapter/Adapter/Pipeline.swift) to facilitate periodic commands, which – for supported adapters – get translated into the appropriate AT commands to allow handling them on the adapter's microcontroller. For non-supported adapters, I will add a way to synthesize these.

> Do you know who I am by the way?

I don't, but I'm eager to learn! From a quick look at the issues you have commented on, it looks like you sport an intimate knowledge of the TriCore microcontroller, which I think is at the heart of some ECUs I work with :-)

**Comment by brandonros** [comment]
https://tpe-europe.de/ is this your client?

**Comment by mickeyl** [comment]
It would be quite unprofessional from me to disclose any clients, so if they were, I wouldn't be able to confirm it. Let's keep this issue tracker to discuss technical stuff :-)
